import Head from 'next/head'
import CategoryGallery from '../components/categoryGallery'
import CarouselFeed from '../components/carousel'

function Home() {
  return (
    <div>
      <Head>
        <title>Daily Life</title>
        <meta name="description" content="Generated by " />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CategoryGallery />
      <CarouselFeed />
    </div>
  )
}

export default Home;
