import Head from 'next/head'
import CategoryGallery from '../components/categoryGallery'
import CarouselFeed from '../components/carousel'
import { useEffect } from 'react'
import { useDispatch } from "react-redux";
import { addProducts } from "../slices/cartSlice"

function Home({products}) {
  const dispatch = useDispatch()

  useEffect(() => {
    dispatch(addProducts(products))
  }, [products])

  return (
    <div>
      <Head>
        <title>Daily Life</title>
        <meta name="description" content="Generated by " />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CategoryGallery />
      <CarouselFeed />
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch(`${process.env.BACKEND_API_BASE}/store/api/`)
  const products = await res.json()

  return {
      props: { products },
  }
}

export default Home;